In [2]:
scores=[85,67,52]
new_scores=[]

for score in scores:
    new_scores.append(score+8)

new_scores

[93, 75, 60]

In [4]:
# list complehension (快速建立list)

scores=[85,67,52]
new_scores=[score+8 for score in scores]  #complehension裡面一定要放for in

new_scores

[93, 75, 60]

In [ ]:
scores=[85,67,52]
score*2

104

In [6]:
[85,67,52]+[93, 75, 60]

[85, 67, 52, 93, 75, 60]

In [ ]:
# numpy是另一種python提供的資料結構，用終端機cmd輸入pip install numpy
# 小技巧：建一個requirements.txt檔案，把套件名寫在裡面。於cmd終端機輸入pip install -requirements.txt  *會一次灌完，重複的會自己略過不再重灌。

import numpy as np   #給numpy一個小名np

scores=np.array([85,67,52])  #array是function
print(type(scores))  #type是numpy.ndarray
scores+8  #numpy才能這樣寫，如果是list類型不可這樣操作

<class 'numpy.ndarray'>


array([93, 75, 60])

In [10]:
scores.sum()
scores.mean()
scores.std()
scores.min()
scores.max()
np.median(scores)

np.float64(67.0)

In [ ]:
students=np.array([
    [67,94,65],
    [78,92,68],
    [59,92,87]
    ])

students  #學生1~3，分數國英數

array([[67, 94, 65],
       [78, 92, 68],
       [59, 92, 87]])

In [ ]:
#  ndarray常用的屬性
## ndim:維數 size:元素數 shape:資料形狀(列,欄) dtype:資料型態(整數,64-bit)
students.ndim, students.size, students.shape, students.dtype

(2, 9, (3, 3), dtype('int64'))

In [19]:
#兩種寫法都可以抓到一樣的資料
students[0]
students[0,:]

array([67, 94, 65])

In [23]:
#前兩位學生的所有分數
students[0:2]

array([[67, 94, 65],
       [78, 92, 68]])

In [22]:
#最後兩位學生的所有分數
students[-2:]

array([[78, 92, 68],
       [59, 92, 87]])

In [24]:
#國文分數
students[:,0]

array([67, 78, 59])

In [ ]:
#國文、英文分數
students[:,:2]

array([[67, 94],
       [78, 92],
       [59, 92]])